// Flutter icons CuidaPet
// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

class CuidaPetIcons {
  CuidaPetIcons._();

  static const _kFontFam = 'CuidaPet';
  static const String? _kFontPkg = null;

  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
